### ISSUE TITLE
[macOS] 1.7.1 broken on Sonoma / aarch64 (apparently only on this specific configuration)

### ISSUE THREAD

**Issue by barracuda156** [nanomsg/nng#1766]
The problem seems to affect only macOS Sonoma and only for `aarch64`:

```
:info:build FAILED: CMakeFiles/nng.dir/src/nng_legacy.c.o 
:info:build /usr/bin/clang -DNNG_ENABLE_STATS -DNNG_HAVE_ARC4RANDOM=1 -DNNG_HAVE_BACKTRACE=1 -DNNG_HAVE_BUS0 -DNNG_HAVE_FLOCK=1 -DNNG_HAVE_GETPEEREID=1 -DNNG_HAVE_KQUEUE=1 -DNNG_HAVE_LANGINFO=1 -DNNG_HAVE_LOCALPEERCRED=1 -DNNG_HAVE_LOCALPEERPID=1 -DNNG_HAVE_LOCKF=1 -DNNG_HAVE_MSG_CONTROL=1 -DNNG_HAVE_PAIR0 -DNNG_HAVE_PAIR1 -DNNG_HAVE_PTHREAD_ATFORK_PTHREAD=1 -DNNG_HAVE_PTHREAD_SETNAME_NP=1 -DNNG_HAVE_PUB0 -DNNG_HAVE_PULL0 -DNNG_HAVE_PUSH0 -DNNG_HAVE_REP0 -DNNG_HAVE_REQ0 -DNNG_HAVE_RESPONDENT0 -DNNG_HAVE_SEMAPHORE_PTHREAD=1 -DNNG_HAVE_SOCKETPAIR=1 -DNNG_HAVE_STDATOMIC=1 -DNNG_HAVE_STRCASECMP=1 -DNNG_HAVE_STRLCPY=1 -DNNG_HAVE_STRNCASECMP=1 -DNNG_HAVE_STRNLEN=1 -DNNG_HAVE_SUB0 -DNNG_HAVE_SURVEYOR0 -DNNG_HAVE_UNIX_SOCKETS=1 -DNNG_HIDDEN_VISIBILITY -DNNG_MAX_EXPIRE_THREADS=8 -DNNG_MAX_POLLER_THREADS=8 -DNNG_MAX_TASKQ_THREADS=16 -DNNG_PLATFORM_DARWIN -DNNG_PLATFORM_POSIX -DNNG_PRIVATE -DNNG_RESOLV_CONCURRENCY=4 -DNNG_STATIC_LIB -DNNG_SUPP_HTTP -DNNG_SUPP_TLS -DNNG_TLS_ENGINE_FINI=nng_tls_engine_fini_mbed -DNNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed -DNNG_TRANSPORT_FDC -DNNG_TRANSPORT_INPROC -DNNG_TRANSPORT_IPC -DNNG_TRANSPORT_TCP -DNNG_TRANSPORT_TLS -DNNG_TRANSPORT_WS -DNNG_TRANSPORT_WSS -D_GNU_SOURCE -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D_THREAD_SAFE -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/include -pipe -Os -DNDEBUG -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -Wall -Wextra -fno-omit-frame-pointer   -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -mmacosx-version-min=14.0 -std=gnu99 -MD -MT CMakeFiles/nng.dir/src/nng_legacy.c.o -MF CMakeFiles/nng.dir/src/nng_legacy.c.o.d -o CMakeFiles/nng.dir/src/nng_legacy.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/nng_legacy.c
:info:build In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/nng_legacy.c:11:
:info:build In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/nng_impl.h:33:
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:28:45: error: unexpected type name 'uint64_t': expected identifier
:info:build void nni_init_set_param(nng_init_parameter, uint64_t value);
:info:build                                             ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:28:54: error: expected ')'
:info:build void nni_init_set_param(nng_init_parameter, uint64_t value);
:info:build                                                      ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:28:24: note: to match this '('
:info:build void nni_init_set_param(nng_init_parameter, uint64_t value);
:info:build                        ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:28:25: error: a parameter list without types is only allowed in a function definition
:info:build void nni_init_set_param(nng_init_parameter, uint64_t value);
:info:build                         ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:31:29: error: unknown type name 'nng_init_parameter'
:info:build uint64_t nni_init_get_param(nng_init_parameter parameter, uint64_t default_value);
:info:build                             ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_nng/nng/work/nng-1.7.1/src/core/init.h:34:29: error: unknown type name 'nng_init_parameter'
:info:build void nni_init_set_effective(nng_init_parameter p, uint64_t value);
:info:build                             ^
:info:build 5 errors generated.
```
Complete log: 
[nng_sonoma_aarch64.log](https://github.com/nanomsg/nng/files/13968664/nng_sonoma_aarch64.log)

On Sonoma / x86_64 there is no failure: https://build.macports.org/builders/ports-14_x86_64-builder/builds/26675/steps/install-port/logs/stdio
There is also no error on Ventura / aarch64: https://build.macports.org/builders/ports-13_arm64-builder/builds/48168/steps/install-port/logs/stdio
In fact, looks like it builds fine on every other system aside of 14.2.1 for aarch64.

**Comment by kencu** [comment]
ChatGPT is getting so good for these:

"
It seems like there might be a syntax error or an issue with the include statements in your code. The error message "unexpected type name 'uint64_t': expected identifier" suggests that the compiler is not recognizing the type uint64_t.

To resolve this issue, you should make sure that you have included the necessary header file that defines uint64_t. In C, the uint64_t type is typically defined in the <inttypes.h> header file. Make sure you have the following include at the beginning of your code:

```
#include <inttypes.h>

```

"

**Comment by barracuda156** [comment]
@kencu Thank you, let me try. (Wonder why this only affects Sonoma on arm64.)

**Comment by barracuda156** [comment]
@kencu Oh wow, I reran the build now, and it compiled without issues this time. No idea why.

Closing this, since though it is inexplicable, the failure do not repeat.
