### ISSUE TITLE
Undefined reference to `nni_atomic_swap` & `nni_atomic_cas`(Built by gcc 4.8.5 )

### ISSUE THREAD

**Issue by alvin1221** [nanomsg/nng#1586]
**Describe the bug**
Functions `nni_atomic_swap` and `nni_atomic_cas` undefined when complie condition is 'NNI_GCC_VERSION >= 40700 || \
    defined(__clang__) ':  [posix_atomic.c](https://github.com/nanomsg/nng/blob/master/src/platform/posix/posix_atomic.c)
```
 undefined reference to `nni_atomic_swap'
 undefined reference to `nni_atomic_cas'
```

**Expected behavior**
Complie success.

**Actual Behavior**
Build failed: 
 undefined reference to `nni_atomic_swap`
 undefined reference to `nni_atomic_cas`

**To Reproduce**
Build with gcc-4.8.5 on posix platform.

** Environment Details **
 - NNG version: latest master
 - Operating system and version: ubuntu 18
 - Compiler and language used: gcc 4.8.5 ,C 
 - Shared or static library: static

**Additional context**
