### PR TITLE
Update win_tcpconn.c

### LINKED ISSUE #1676: compile with clang version 16.0.5
**Describe the bug**
nanomsg does not compile using clang version 16.0.5

**Expected behavior**
should compile

**Actual Behavior**
Got this error message:
`
  C:\PROGRA~1\MICROS~4\2022\PROFES~1\VC\Tools\Llvm\x64\bin\clang.exe -c nng/src/platform/windows/win_tcpconn.c

win_tcpconn.c(450,17): error GC4FBD38D: incompatible function pointer types assigning to 'void (*)(void *, nng_aio *)' (aka 'void (*)(void *, struct nng_aio *)') from 'void (nni_tcp_conn *, nni_aio *)' (aka 'void (struct nni_tcp_conn *, struct nng_aio *)') [-Wincompatible-function-pointer-types]
  
          c->ops.s_recv  = tcp_recv;
`

**To Reproduce**
Just install last clang version 16.0.5 and compile with it

** Environment Details **
 - NNG version: v1.5.2
 - Operating system and version: Windows 10 Enterprise / Version 21H2
 - Compiler and language used: clang version 16.0.5
 - Visual studio used: Version 17.7.0

### PR DESCRIPTION
**Pull request by NissimBendanan**
fixes #1676 nanomsg does not compile using clang version 16.0.5

### CODE REVIEW

**Comment by shikokuchuo** [comment]
@gdamore I've been running with this change and good to merge from my perspective.

**Comment by NissimBendanan** [comment]
got the following timeout error, is it OK for you? or someone can re trigger the tests? what next steps to merge this PR?
Thanks
Nissim

`
46/80 Test #46: nng.ipc .....................................***Timeout   5.53 sec
=== RUN: IPC Transport
`

**Comment by gdamore** [comment]
I've been stalling on this because I'm not actually sure this change is "correct" -- I get that it makes the code compile, but it may be more correct to match the types elsewhere.  I will try to examine more closely soon.

**Comment by NissimBendanan** [comment]
Hi,

In nni_win_tcp_init, all handlers (apart tcp_recv) use the same “type of” signature that get as first argument a void pointer and then cast the arg to nni_tcp_conn *c:

      c->ops.s_close = tcp_close;
      c->ops.s_free  = tcp_free;
      c->ops.s_send  = tcp_send;
      c->ops.s_recv  = tcp_recv;
      c->ops.s_get   = tcp_get;
      c->ops.s_set   = tcp_set;

struct nng_stream {
      void (*s_free)(void *);
      void (*s_close)(void *);
      void (*s_recv)(void *, nng_aio *);
      void (*s_send)(void *, nng_aio *);
      int (*s_get)(void *, const char *, void *, size_t *, nni_type);
      int (*s_set)(void *, const char *, const void *, size_t, nni_type);
};

For tcp_recv, the original signature didn’t follow the declaration of struct nng_stream{ s_recv }.
The last version of clang exit with error on this mismatch.

Can you please check?

Thanks
Nissim

**Comment by gdamore** [comment]
Checked, finally.  Sorry for the delay.  Thanks for the submission.
