### ISSUE TITLE
compile with clang version 16.0.5

### ISSUE THREAD

**Issue by NissimBendanan** [nanomsg/nng#1676]
**Describe the bug**
nanomsg does not compile using clang version 16.0.5

**Expected behavior**
should compile

**Actual Behavior**
Got this error message:
`
  C:\PROGRA~1\MICROS~4\2022\PROFES~1\VC\Tools\Llvm\x64\bin\clang.exe -c nng/src/platform/windows/win_tcpconn.c

win_tcpconn.c(450,17): error GC4FBD38D: incompatible function pointer types assigning to 'void (*)(void *, nng_aio *)' (aka 'void (*)(void *, struct nng_aio *)') from 'void (nni_tcp_conn *, nni_aio *)' (aka 'void (struct nni_tcp_conn *, struct nng_aio *)') [-Wincompatible-function-pointer-types]
  
          c->ops.s_recv  = tcp_recv;
`

**To Reproduce**
Just install last clang version 16.0.5 and compile with it

** Environment Details **
 - NNG version: v1.5.2
 - Operating system and version: Windows 10 Enterprise / Version 21H2
 - Compiler and language used: clang version 16.0.5
 - Visual studio used: Version 17.7.0
